name: hmis
description: A new Flutter project.
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.0.2
  font_awesome_flutter: ^10.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_native_splash: ^2.4.1
  states_rebuilder: ^6.4.0
  uuid: ^4.4.0
  hive_flutter: ^1.1.0
  manager:
    path: ..//manager
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  go_router: ^14.6.1
  equatable: ^2.0.7
  objectbox: ^4.0.3
  objectbox_generator: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  path_provider: ^2.1.5
  path: ^1.9.0
  package_info_plus: ^8.1.1
  hydrated_bloc: ^9.1.5
  shared_preferences: ^2.3.5
dev_dependencies:
  freezed:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.7.1    
flutter:
  assets:
    - assets/
  uses-material-design: true
flutter_native_splash:
  image: "assets/hospital.png"
  color: "#000000"
  background_image: "assets/hospital_bg.png"

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/hospital.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/hospital.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/hospital.png"
    icon_size: 72 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/hospital.png"
# dart run flutter_native_splash:create
# dart run flutter_launcher_icons